This is a testharness.js-based test.
FAIL navigator.wakeLock.request() aborts if the document is not active. promise_rejects_dom: Inactive document, so must throw NotAllowedError function "function() { throw e }" threw an exception from the wrong global
FAIL navigator.wakeLock.request() aborts if the document is active, but not fully active. promise_rejects_dom: Active, but not fully active, so must throw NotAllowedError function "function() { throw e }" threw an exception from the wrong global
Harness: the test ran to completion.

